[project]
name = "xcube" # PYPI RENAME THIS LINE (do not remove this comment, see #1010)
version = "1.14.0.dev0"
dynamic = ["readme"]
authors = [
  {name = "xcube Development Team"}
]
description = """\
  xcube is a Python package for generating and exploiting \
  data cubes powered by xarray, dask, and zarr. \
  """
keywords = [
  "analysis ready data", "data science",
  "datacube", "xarray", "zarr"
]
license = {text = "MIT"}
requires-python = ">=3.10,<3.14"
dependencies = [
"affine>=2.2",
  "affine>=2.2",
  "altair",
  "botocore>=1.34.51",
  "cftime>=1.6.3",
  "click>=8.2.0",
  "cmocean>=2.0",
  "chartlets>=0.2.1",
  "cryptography",  # pyjwt optional dependency; see PR #1199
  "dask>=2024.8",
  "dask-image>=0.6",
  "deprecated>=1.2",
  "distributed>=2021.6",
  "fiona>=1.8",
  "fsspec>=2021.6",
  "gdal>=3.0",
  "geopandas>=0.8",
  "jdcal>=1.4",
  "jsonschema>=3.2",
  "mashumaro",
  "matplotlib>=3.8.3,<4",
  "netcdf4>=1.5",
  "numba>=0.52",
  "numcodecs>=0.12.1",
  "numpy>=1.16",
  "pandas>=1.3,<3",
  "pillow>=6.0",
  "pyjwt>=2.5",
  "pyproj>=3.0",
  "pyyaml>=5.4",
  "rasterio>=1.2",
  "requests>=2.25",
  "rfc3339-validator>=0.1",
  "rioxarray>=0.11",
  "s3fs>=2021.6",
  "setuptools>=41.0",
  "shapely>=1.6",
  "tabulate>=0.9",
  "tornado>=6.0,<6.5",
  "urllib3>=2.0",
  "xarray>=2024.7",
  "zarr>=3.1.4,<4",
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
  "Typing :: Typed",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX",
  "Operating System :: Unix",
  "Operating System :: MacOS",
]

# entry point xcube's CLI
[project.scripts]
xcube = "xcube.cli.main:main"

# entry point xcube's default extensions
[project.entry-points.xcube_plugins]
xcube = "xcube.plugin:init_plugin"

[build-system]
requires = ["setuptools >= 61.2.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"xcube" = ["py.typed"]
"xcube.webapi.meta" = [
    "data/openapi.html",
]
"xcube.webapi.viewer" = [
    "dist/*", "dist/**/*",
]

[tool.setuptools.dynamic]
readme = {file = "README.md", content-type = "text/markdown"}

[tool.setuptools.packages.find]
exclude = [
  "test*",
  "doc*"
]

[project.urls]
Documentation = "https://xcube.readthedocs.io/en/latest/"
Source = "https://github.com/xcube-dev/xcube"
Download = "https://pypi.org/project/xcube-core/#files"
Tracker = "https://github.com/xcube-dev/xcube/issues"
"Release notes" = "https://github.com/xcube-dev/xcube/releases"
Changelog = "https://github.com/xcube-dev/xcube/blob/main/CHANGES.md"

# --- Tool configuration

[tool.isort]
known_first_party = ["xcube"]
line_length = 88
profile = "black"
skip = [".idea", ".github", ".pixi", "htmlcov", "site"]

[tool.black]
line-length = 88

[tool.ruff]
include = [
    "notebooks/**/*.py",
    "xcube/**/*.py",
]

[tool.ruff.lint]
ignore = ["E501", "I001"]
isort = { relative-imports-order = "closest-to-furthest" }
per-file-ignores = { "*.ipynb" = ["E402"] }
select = ["I", "F", "E"]

[tool.coverage.report]
omit = []

[tool.mypy]
python_version = "3.12"
check_untyped_defs = true
disable_error_code = ["valid-type", "import-untyped"]

# --- Pixi tool configuration

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64"]

[tool.pixi.pypi-dependencies]
xcube = { path = ".", editable = true }

[tool.pixi.dependencies]
# python
python = ">=3.10,<3.14"
# library dependencies
altair = "*"  # for chartlets
affine = ">=2.2"
botocore = ">=1.34.51"
cftime = ">=1.6.3"
chartlets = ">=0.2.1"
click = ">=8.2.0"  # TODO: drop in favor of typer
cmocean = ">=2.0"
cryptography = "*"
dask = ">=2024.8"
dask-image = ">=0.6"
deprecated = ">=1.2"
distributed = ">=2021.6"
fiona = ">=1.8"
fsspec = ">=2021.6"
gdal = ">=3.0"
geopandas = ">=0.8"
jdcal = ">=1.4"
jsonschema = ">=3.2"
libgdal-jp2openjpeg = "*"
libjxl = "<=0.11.2"  # because >=0.12.0 causes CI failures with rasterio/GDAL binaries
mashumaro = "*"
matplotlib-base = ">=3.8.3,<4"
netcdf4 = ">=1.5"
numba = ">=0.52"
numcodecs = ">=0.12.1"
numpy = ">=1.16"
pandas = ">=1.3,<3"
pillow = ">=6.0"
pyjwt = ">=2.5"
pyproj = ">=3.0"
pyyaml = ">=5.4"
rasterio = ">=1.2"
requests = ">=2.25"
rfc3339-validator = ">=0.1"  # for python-jsonschema date-time format validation
rioxarray = ">=0.11"
s3fs = ">=2021.6"
setuptools = ">=41.0"  # TODO: drop in favor of stdlib
shapely = ">=1.6"
tabulate = ">=0.9"
tornado = ">=6.0,<6.5"
urllib3 = ">=2.0"
xarray = ">=2024.7"
zarr = ">=3.1.4,<4"
# Pixi IDE integration
pixi-pycharm = ">=0.0.11"
# Code formatting & checking
isort = "*"
flake8 = ">=3.7"  # TODO: drop in favor of ruff check
ruff = "*"
mypy = "*"
# Unit-testing
pytest = "*"
pytest-cov = "*"
# Extra unit testing dependencies
kerchunk = ">=0.2.8"
moto = ">=4"
pytz = "*"  # for test/util/test_timeindex.py
requests-mock = ">=1.8"
werkzeug = "*"

# pixi run ...

[tool.pixi.tasks]
# Top-level tasks
doc-serve = "mkdocs serve"
doc-build = "mkdocs build"
jl = "jupyter-lab"
tests = "pytest"
# The following are helpers for composite tasks that use `depends-on`
format-with-isort = "isort src tests"
format-with-ruff = "ruff format src tests"
check-with-ruff = "ruff check src"
check-with-mypy = "mypy src"
cov-base = "pytest --cov src/sen4cap_client --cov-report= --cov-append tests"
cov-report-html = "coverage html -d .cov-report && coverage report"
cov-report-xml = "coverage xml -o coverage.xml && coverage report"

# pixi run format

[tool.pixi.tasks.format]
depends-on = ["format-with-isort", "format-with-ruff"]

# pixi run checks

[tool.pixi.tasks.checks]
depends-on = ["check-with-ruff", "check-with-mypy"]

# pixi run coverage

[tool.pixi.tasks.coverage]
depends-on = ["cov-base", "cov-report-html"]

# pixi run coverage-ci

[tool.pixi.tasks.coverage-ci]
depends-on = ["cov-base", "cov-report-xml"]
