name: rtd-xcube
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python >=3.9
  # Required
  - adlfs >=2023.1  # for azure blob filesystem
  - affine >=2.2
  - click >=8.0
  - cmocean >=2.0
  - dask >=2021.6
  - dask-image >=0.6
  - deprecated >=1.2
  - distributed >=2021.6
  - fiona >=1.8
  - fontconfig
  - fsspec >=2021.6
  - gdal >=3.0
  - geopandas >=0.8
  - jdcal >=1.4
  - jsonschema >=3.2
  - matplotlib-base >=3.0
  - netcdf4 >=1.5
  - numba >=0.52
  - numpy >=1.16
  - openssl
  - pandas >=1.3,<2
  - pillow >=6.0
  - pyjwt >=1.7
  - pyproj >=3.0
  - pyyaml >=5.4
  - rasterio >=1.2
  - requests >=2.25
  - requests-oauthlib >=1.3
  - rfc3339-validator >=0.1  # for python-jsonschema date-time format validation
  - rioxarray >=0.11
  - s3fs >=2021.6
  - scipy >=1.6.0
  - setuptools >=41.0
  - shapely >=1.6
  - tornado >=6.0
  - urllib3 >=1.26
  - werkzeug <2.2  # >=2.2 slows down S3 tests (deps: moto->flask->werkzeug)
  - xarray >=2022.6, <= 2024.6
  - xvec
  - zarr >=2.11
  # Required by Coiled
  # These are very likely transitive deps anyway
  - lz4
  - python-blosc
  # Testing
  - flake8 >=3.7
  - kerchunk
  - moto >=4
  - pytest >=4.4
  - pytest-cov >=2.6
  - requests-mock >=1.8
  # RTD specials
  - pip:
      - sphinx
      - sphinx_rtd_theme
      - sphinx-argparse
      - sphinx-autodoc-annotation
      - sphinx-markdown-tables
      - recommonmark
      - mock
