Viewer:
  Augmentation:
    Path: ""
    Extensions:
      - demo_panels.ext
  Persistence:
     Path: memory://states

DatasetChunkCacheSize: 100M

DataStores:
  - Identifier: xcube-examples
    StoreId: s3
    StoreParams:
      root: xcube-examples
      storage_options:
        anon: true
    Datasets:
      - Path: openSR_nordfriesland_S2L2A_selected_dates_10m-v4.levels
        Identifier: waddensea
        Title: Wadden Sea Nordfriesland
        Description: >-
          The [**Wadden Sea**](https://en.wikipedia.org/wiki/Wadden_Sea) 
          (Dutch: _Waddenzee_ [ˈʋɑdə(n)zeː]; 
          German: _Wattenmeer_ [ˈvatn̩ˌmeːɐ̯];
          Low German: _Wattensee_ or _Waddenzee_; 
          Danish: _Vadehavet_;
          West Frisian: _Waadsee_; 
          North Frisian: _di Heef_) 
          is an [intertidal zone](https://en.wikipedia.org/wiki/Intertidal_zone) 
          in the southeastern part of the 
          [North Sea](https://en.wikipedia.org/wiki/North_Sea). 
          It lies between the coast of northwestern continental Europe and the 
          range of low-lying Frisian Islands, forming a shallow body of water 
          with tidal flats and wetlands. It has a high biological diversity 
          and is an important area for both breeding and migrating birds.
          ![Wadden Sea](https://upload.wikimedia.org/wikipedia/commons/e/e7/13-09-29-nordfriesisches-wattenmeer-RalfR-19.jpg)
        Style: waddensea
        Augmentation:
          Path: compute_indexes.py
          Function: compute_indexes
      - Path: cmems_mod_bal_bgc_anfc_P1D-m_2025070115_36m_kattegat.zarr
        Identifier: kattegat
        Title: Kattegat
        Style: kattegat
        Description: >-
            The Kattegat (/ˈkætəɡæt/; Danish: [ˈkʰætəkæt]; 
            Swedish: Kattegatt [ˈkâtːɛˌɡat]) 
            is a sea of roughly 24,000 km2 (9,300 sq mi) bounded by the 
            [Skagerrak](https://en.wikipedia.org/wiki/Skagerrak) in the north, 
            [Jutland](https://en.wikipedia.org/wiki/Jutland) in the west, 
            the [Danish Straits](https://en.wikipedia.org/wiki/Danish_Straits) and 
            [Sjaelland](https://en.wikipedia.org/wiki/Sjaelland) in the south and 
            the Swedish provinces of Bohuslän, Västergötland, Halland and Scania 
            in the east. The [Baltic Sea](https://en.wikipedia.org/wiki/Baltic_Sea) 
            drains into the Kattegat through the Danish Straits. 
            ![Kattegat](https://upload.wikimedia.org/wikipedia/commons/c/c2/Carte_Skagerrak-Kattegat2.png)

Styles:
  - Identifier: waddensea
    ColorMappings:
      B01:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      B02:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      B03:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      B04:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      B05:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      B06:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      B07:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      B08:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      B8A:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      B09:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      B10:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      B11:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      B12:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      SCL:
        ColorBar: "Accent"
        ValueRange: [ 0, 255 ]
      rgb:
        Red:
          Variable: B04
          ValueRange: [0., 0.25]
        Green:
          Variable: B03
          ValueRange: [0., 0.25]
        Blue:
          Variable: B02
          ValueRange: [0., 0.25]

  - Identifier: kattegat
    ColorMappings:
      chl:
        ColorBar: "viridis"
        ValueRange: [0, 15]
      zooc:
        ColorBar: "viridis"
        ValueRange: [0, 15]
      zsd:
        ColorBar: "viridis"
        ValueRange: [0, 15]

ServiceProvider:
  ProviderName: "Brockmann Consult GmbH"
  ProviderSite: "https://www.brockmann-consult.de"
