# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: publish to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.10.1
      with:
        pixi-version: v0.77.1
        run-install: false
    - name: Build package
      run: |
        LINE_NB=$(grep -n 'name = "xcube" # PYPI RENAME THIS LINE' pyproject.toml | cut -f1 -d:)
        sed -i "${LINE_NB}s/.*/name = 'xcube-core'/" pyproject.toml
        pixi exec --spec python-build -- python -m build
    - name: Publish to PyPI
      run: pixi exec --spec twine -- python -m twine upload --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} dist/*
